### PR TITLE
fix(cursor): fix iterator impl for cursor

### LINKED ISSUE #33: implementation of `Iterator` for `Cursor` is wrong
I've recently started adding `Cursor`s to `intruder_alarm::doubly::List` (#9) in a branch. However, I've hit a fairly serious bug in the implementation of `Iterator` for `Cursor`. `Cursor`s acting as `Iterator`s will skip the first element of the data structure they cursor over.

### The bug

`Iterator::next` is currently implemented for `Cursor` by calling `self.next_item()`:

https://github.com/hawkw/alarm/blob/41a3b9d89c9e8a56266fc8a56aaf4cd0e30bc8b6/intruder_alarm/src/cursor.rs#L128-L136

However, `Cursor::next_item` will advance the cursor to the next element in the list _and then_ call `Cursor::get`, getting the current element:

https://github.com/hawkw/alarm/blob/41a3b9d89c9e8a56266fc8a56aaf4cd0e30bc8b6/intruder_alarm/src/cursor.rs#L55-L58

In my branch, I'm creating my `Cursor`s pointing at the head element of the list:

https://github.com/hawkw/alarm/blob/d5e1a1002212d2eb511109d5c9f7b3a124683fb8/intruder_alarm/src/doubly/mod.rs#L337-L344

Since the `Cursor` _already_ points at the head element when `Iterator::next` is called on it for the first time, `Cursor::next_item` will advance the cursor and return _the next_ item. The iterator never returns the head element.

### How to fix it

We have a couple options here. We _could_ special-case the `Iterator` impl to check if it's pointing at the first element, but this seems kind of inelegant. 

I think a better option is to rewrite `Iterator::next` for `Cursor` to call `self.get()`, store the return value in a temporary variable, call `self.move_forward()`, and _then_ return the result of the call to `get`. If we thought this functionality might be useful in contexts other than in the `Iterator` implementation, we could also consider encapsulating it in a new function on `Cursor` (maybe called `get_and_advance` or something?), but this is probably unnecessary.

### PR DESCRIPTION
**Pull request by leshow**
closes #33 
I think this is what you were asking for 

Please let me know if any changes need to be made

### CODE REVIEW

File: intruder_alarm/src/cursor.rs [hunk 1]
```diff
@@ -111,36 +111,34 @@ pub trait CursorMut<'a, T: 'a>: Cursor<Item = &'a mut T> {
...
-impl<I> Iterator for Cursor<Item = I>{
+impl<I> Iterator for Cursor<Item = I> {
     type Item = I;
 
     #[inline]
     fn next(&mut self) -> Option<Self::Item> {
-        self.next_item()
+        let item = self.get();
+        self.move_forward();
+        item
```
Comment (hawkw) [inline intruder_alarm/src/cursor.rs:133]: Yup, that looks right! 👍

**Review by hawkw — CHANGES_REQUESTED** [review]
The fix looks correct! 

There are a lot of unrelated formatting changes (I'm guessing rustfmt?) in this diff, and I'd like it if those could be merged separately for `git blame` reasons. Once that's resolved, let's get this merged!

**Comment by leshow** [comment]
I think after I rebase the diff will go away, so hold on I'll amend

**Review by hawkw — APPROVED** [review]
